//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchMakingMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Games\\World_of_Warships")]
        public string InstallDirectory {
            get {
                return ((string)(this["InstallDirectory"]));
            }
            set {
                this["InstallDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04c8800d343d496e7ae9c94ba6e51a0b")]
        public string AppIdNA {
            get {
                return ((string)(this["AppIdNA"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NA")]
        public string Region {
            get {
                return ((string)(this["Region"]));
            }
            set {
                this["Region"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8c4616d4f59f9e915d214c514f7661f2")]
        public string AppIdEU {
            get {
                return ((string)(this["AppIdEU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("92669bcd3cb4978e78a387bdc2e7f8d6")]
        public string AppIdRU {
            get {
                return ((string)(this["AppIdRU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a7079ba49e5487b6936aed9176c13968")]
        public string AppIdSEA {
            get {
                return ((string)(this["AppIdSEA"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#401070")]
        public string Color9 {
            get {
                return ((string)(this["Color9"]));
            }
            set {
                this["Color9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#793db6")]
        public string Color8 {
            get {
                return ((string)(this["Color8"]));
            }
            set {
                this["Color8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#3972c6")]
        public string Color7 {
            get {
                return ((string)(this["Color7"]));
            }
            set {
                this["Color7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4099bf")]
        public string Color6 {
            get {
                return ((string)(this["Color6"]));
            }
            set {
                this["Color6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4d7326")]
        public string Color5 {
            get {
                return ((string)(this["Color5"]));
            }
            set {
                this["Color5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ccb800")]
        public string Color4 {
            get {
                return ((string)(this["Color4"]));
            }
            set {
                this["Color4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#cc7a00")]
        public string Color3 {
            get {
                return ((string)(this["Color3"]));
            }
            set {
                this["Color3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#cd3333")]
        public string Color2 {
            get {
                return ((string)(this["Color2"]));
            }
            set {
                this["Color2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#930d0d")]
        public string Color1 {
            get {
                return ((string)(this["Color1"]));
            }
            set {
                this["Color1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Token {
            get {
                return ((string)(this["Token"]));
            }
            set {
                this["Token"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.worldofwarships.com")]
        public string BaseUrlNA {
            get {
                return ((string)(this["BaseUrlNA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.worldofwarships.eu")]
        public string BaseUrlEU {
            get {
                return ((string)(this["BaseUrlEU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.worldofwarships.ru")]
        public string BaseUrlRU {
            get {
                return ((string)(this["BaseUrlRU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.worldofwarships.asia")]
        public string BaseUrlSEA {
            get {
                return ((string)(this["BaseUrlSEA"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150; 100; 80; 60; 40; 30; 20; 10; 0")]
        public string BattleLimits {
            get {
                return ((string)(this["BattleLimits"]));
            }
            set {
                this["BattleLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90; 80; 70; 60; 50; 40; 30; 20; 0")]
        public string WinLimits {
            get {
                return ((string)(this["WinLimits"]));
            }
            set {
                this["WinLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,5; 1,3; 1,1; 1,0; 0,8; 0,6; 0,4; 0,2; 0")]
        public string FragsLimits {
            get {
                return ((string)(this["FragsLimits"]));
            }
            set {
                this["FragsLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500; 1200; 1000; 900; 800; 600; 500; 400; 0")]
        public string XpLimits {
            get {
                return ((string)(this["XpLimits"]));
            }
            set {
                this["XpLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75000; 65000; 55000; 45000; 35000; 25000; 15000; 10000; 0")]
        public string DmgLimits {
            get {
                return ((string)(this["DmgLimits"]));
            }
            set {
                this["DmgLimits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public double BattleWeight {
            get {
                return ((double)(this["BattleWeight"]));
            }
            set {
                this["BattleWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1")]
        public double FragsWeight {
            get {
                return ((double)(this["FragsWeight"]));
            }
            set {
                this["FragsWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double XpWeight {
            get {
                return ((double)(this["XpWeight"]));
            }
            set {
                this["XpWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double DmgWeight {
            get {
                return ((double)(this["DmgWeight"]));
            }
            set {
                this["DmgWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double WinWeight {
            get {
                return ((double)(this["WinWeight"]));
            }
            set {
                this["WinWeight"] = value;
            }
        }
    }
}
